# seed for the random number generators, to make things reproducible
seed: 0

# define th number of cross validations to perform
n_cross_validations : 5

# telescope_type_key: telescope_type_name
#telescope_events_key: telescope_events
#array_events_key: array_events
#runs_key: runs


multiple_telescopes: False


disp:
  disp_regressor : |
    ensemble.RandomForestRegressor(
        n_estimators=100,
        max_features='sqrt',
        n_jobs=-1,
        max_depth=20,
    )

  sign_classifier: |
    ensemble.RandomForestClassifier(
        n_estimators=100,
        max_features='sqrt',
        n_jobs=-1,
        max_depth=20,
    )

  coordinate_transformation: CTA

  source_az_column: source_azimuth
  source_zd_column: source_zenith 
  pointing_az_column: pointing_azimuth
  pointing_zd_column: pointing_zenith 

  cog_x_column: x  
  cog_y_column: y  
  delta_column: psi_deg
  #array_event_column: array_event_id


  # randomly sample the data if you dont want to use the whole set
  n_signal : 50000

  features:
    #- num_pixel_in_shower
    - intensity
    - width
    - length
    - leakage
    - r
    - kurtosis
    - skewness
    - time_gradient
    - intercept
    #- deviation

  feature_generation:
    needed_columns:
      - width
      - length
    features:
      elongation: width / length
