# seed for the random number generators, to make things reproducible
seed: 0
true_energy_column: mc_energy

# define th number of cross validations to perform
n_cross_validations : 5

# telescope_type_key: telescope_type_name
#telescope_events_key: telescope_events
#array_events_key: array_events
#runs_key: runs


multiple_telescopes: False


disp:
  disp_regressor : |
    ensemble.RandomForestRegressor(
        n_estimators=100,
        max_features='sqrt',
        n_jobs=-1,
        max_depth=20,
    )

  sign_classifier: |
    ensemble.RandomForestClassifier(
        n_estimators=100,
        max_features='sqrt',
        n_jobs=-1,
        max_depth=20,
    )

  coordinate_transformation: CTA

  source_az_column: source_azimuth
  source_az_unit: deg
  source_zd_column: source_zenith 
  source_zd_unit: deg
  pointing_az_column: pointing_azimuth
  pointing_az_unit: deg
  pointing_zd_column: pointing_zenith
  pointing_zd_unit: deg

  cog_x_column: x  
  cog_y_column: y  
  delta_column: psi
  delta_unit: rad
  #array_event_column: array_event_id


  # randomly sample the data if you dont want to use the whole set
  n_signal : 50000

  features:
    - intensity
    - log_intensity
    - width
    - length
    - n_pixels
    - leakage1_intensity
    - leakage1_pixel
    - leakage2_intensity
    - leakage2_pixel
    - r
    - kurtosis
    - skewness
    - concentration_cog
    - concentration_core
    - time_gradient
    - intercept

  feature_generation:
    needed_columns:
      - width
      - length
      - log_intensity
    features:
      elongation: width / length
      area: width * length * @pi
      log_intensity_area: log_intensity / (width * length * @pi)
